config/routes.rb
AssignmentHub::Application.routes.draw do
  resources :universities

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "forgot_password" => "password_resets#new", :as => "forgot_password"
  get "reminder" => "reminders#new", :as => "remind_me"
  get "course_search" => "courses#search", :as => "course_search"
  get "dashboard" => "dashboard#index", :as => "dashboard"

  match 'attachments_for/:assignment_id' => 'Attachments#index'
  match 'assignments/new_for_course/:course_id' => 'Assignments#new'

  root :to => "courses#index", :as => "home"

  resources :teachers

  resources :attachments

  resources :assignments

  resources :courses do
    get :autocomplete_university_name, :on => :collection
  end

  resources :users
  resources :sessions
  resources :password_resets
  resources :reminders
  

end

app/models/user.rb
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

require 'digest/sha1'

class User < ActiveRecord::Base
  has_many :courses

  # Validation of various parameters. Important: require valid email format, unique username

  before_create :encrypt_password

  validates_length_of :name, :within => 3..15
  validates_length_of :password, :within => 5..40
  validates_presence_of :name, :password, :first, :last, :email
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "Invalid email"
  validates_uniqueness_of :name, :email
  validates_confirmation_of :password

  USERTYPE = [['Normal', '1'],
              ['Admin', '0']]


  def self.authenticate(name, pass)
    user = find_by_name(name)
    if User.encrypt(pass, user.pass_salt) == user.password
      user
    else
      nil
    end
  end

  def check_password(pass)
    self.password == Digest::SHA1.hexdigest(pass+self.pass_salt)
  end

  def encrypt_password()
    self.pass_salt = User.random_string(10) if !self.pass_salt
    self.password = User.encrypt(self.password, self.pass_salt)
  end

  def encrypt_given_password(password)
    if !self.pass_salt
      self.pass_salt = User.random_string(10)
    end
    self.password = password
    self.password = self.password_confirmation = User.encrypt(password, self.pass_salt)
  end

  def forgot_password(name, email)
    user = User.find_by_name(name)
    if user.email == email
      new_pass = User.random_string(10)
      user.encrypt_given_password(new_pass)
      user.save
      Notifications.forgot_password(self.email, self.name, new_pass).deliver
      end
  end

  protected

  def self.encrypt(pass, salt)
    Digest::SHA1.hexdigest(pass+salt)
  end

  def self.random_string(length)
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    new_pass = ""
    1.upto(length) { |i| new_pass << chars[rand(chars.size-1)] }
    return new_pass
  end
end

app/controllers/users_controller.rb
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    if current_user
      @curr = User.find(current_user)
      if @curr.user_type == 0
          @users = User.all
      else
        redirect_to '/' and return
      end
    else
      redirect_to sign_up_path and return
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def login
    if request.post? and params[:user]
      @user = User.new(params[:user])
      user = User.find_by_username(@user.name)
      if user and user.password_matches?(@user.password)
        flash[:notice] = "Logged in!"
      else
        flash[:warning] = "Couldn't log in!"
      end
    end
  end

  def forgot_password
    if request.post? and params[:user]
      @user = User.new(params[:user])
      user = User.find_by_email(@user.email)
      flash[:notice] = "Received email!"
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.js   { render :nothing => true }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

module UsersHelper
end

app/views/users/_form.html.erb
<!--
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-->

<!-- Content -->
<div id="content">
	<%= form_for(@user) do |f| %>
	  <% if @user.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      
	      <% @user.errors.full_messages.each do |msg| %>
			<!-- Message Error -->
			<div class="msg msg-error">
				<p><strong><%= msg %></strong></p>
				<a href="#" class="close">close</a>
			</div>
			<!-- End Message Error -->      
	      <% end %>
      
	    </div>
	  <% end %>

	<!-- Box -->
	<div class="box">
		<!-- Box Head -->
		<div class="box-head">
			<h2>Edit User</h2>
		</div>
		<!-- End Box Head -->
	
		
			<!-- Form -->
			<div class="form">
				<p>
					<span class="req">(Required, max 50 symbols)</span>
					<%= f.label "Username" %>
					<%= f.text_field :name, :class => 'field size1' %>
				</p>

				<p>
				  	<span class="req">(Required, max 100 symbols)</span>
				  	<%= f.label :password %>
				  	<%= f.password_field :password %>
				</p>
              
                <p>
                    <span class="req">(Required, should match password)</span>
                    <%= f.label :password_confirmation %>
                    <%= f.password_field :password_confirmation %>
                </p>
              
				<p>
				  	<span class="req">(Required, max 20 symbols)</span>
				  	<%= f.label "First name" %>
				  	<%= f.text_field :first %>
				</p>
				<p>
				  	<span class="req">(Required, max 20 symbols)</span>
				  	<%= f.label "Last name" %>
				  	<%= f.text_field :last %>
				</p>
				<p>
				  	<span class="req">(Required, max 100 symbols)</span>
				  	<%= f.label "Email address" %>
				  	<%= f.text_field :email %>
				</p>
				<p>
				  	<%= f.label "Phone number" %>
				  	<%= f.text_field :phone %>
				</p>
				<p>
					<span class="req">(Required)</span>
				  	<%= f.label :user_type %>
				  	<%= f.select :user_type, User::USERTYPE  %>
				</p>
			
			</div>
			<!-- End Form -->
		
			<!-- Form Buttons -->
			<div class="buttons">
				<%= link_to 'Back', users_path, :class => 'button' %>
				<%= f.submit 'Submit', :class => 'button' %>
			</div>
			<!-- End Form Buttons -->
	</div>
	<!-- End Box -->

	<% end %>

</div>
<!-- End Content -->

<!-- Sidebar -->
<div id="sidebar">
	
	<!-- Box -->
	<div class="box">
		
		<!-- Box Head -->
		<div class="box-head">
			<h2>Management</h2>
		</div>
		<!-- End Box Head-->
		
		<div class="box-content">
			<%= link_to 'Add New User', new_user_path, :class => 'btn' %>
			<div class="cl">&nbsp;</div>
			
			<p class="select-all"><input type="checkbox" class="checkbox" /><label>select all</label></p>
			<p><a href="#">Delete Selected</a></p>
			
		</div>
	</div>
	<!-- End Box -->
</div>
<!-- End Sidebar -->

app/views/users/index.html.erb
<!--
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-->

<!-- Content -->
<div id="content">
	
	<!-- Box -->
	<div class="box">
		<!-- Box Head -->
		<div class="box-head">
			<h2 class="left">Listing Users</h2>
			<div class="right">
				<label>search users</label>
				<input type="text" class="field small-field" />
				<input type="submit" class="button" value="search" />
			</div>
		</div>
		<!-- End Box Head -->	

		<!-- Table -->
		<div class="table">
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<th width="13"><input type="checkbox" class="checkbox" /></th>
					<th>Username</th>
				    <th>Full Name</th>
				    <th>Email</th>
				    <th>Phone</th>
				    <th>User Type</th>
					<th></th>
				    <th></th>
				    <th></th>
				</tr>

				<% @users.each do |user| %>
				  <tr>
					<td><input type="checkbox" class="checkbox" /></td>
				    <td><%= link_to user.name, user %></td>
				    <td><%= user.first + " " + user.last %></td>
				    <td><%= user.email %></td>
				    <td><%= user.phone %></td>
				    <td><%= user.user_type == 0 ? 'Admin' : 'Normal' %></td>
				    <td><%= link_to '', edit_user_path(user), :class => 'ico edit' %></td>
				    <td><%= link_to '', user, confirm: 'Are you sure?', method: :delete, :class => 'ico del' %></td>
				  </tr>
				<% end if @users %>

			</table>


			<!-- Pagging -->
			<div class="pagging">
				<div class="left">Showing 1-<%= @users.length if @users %> of <%= @users.length if @users %></div>
				<div class="right">
					<a href="#">Previous</a>
					<a href="#">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">245</a>
					<span>...</span>
					<a href="#">Next</a>
					<a href="#">View all</a>
				</div>
			</div>
			<!-- End Pagging -->

		</div>
		<!-- Table -->

	</div>
	<!-- End Box -->

	<%= link_to "Log In", log_in_path %> |
	<%= link_to "Forgot Password", forgot_password_path %>
	
	
</div>
<!-- End Content -->

<!-- Sidebar -->
<div id="sidebar">
	
	<!-- Box -->
	<div class="box">
		
		<!-- Box Head -->
		<div class="box-head">
			<h2>Management</h2>
		</div>
		<!-- End Box Head-->
		
		<div class="box-content">
			<%= link_to 'Add New User', new_user_path, :class => 'btn' %>
			<div class="cl">&nbsp;</div>
			
			<p class="select-all"><input type="checkbox" class="checkbox" /><label>select all</label></p>
			<p><a href="#">Delete Selected</a></p>
			
		</div>
	</div>
	<!-- End Box -->
</div>
<!-- End Sidebar -->

app/views/users/show.html.erb
<!--
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-->

<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.name %>
</p>

<p>
  <b>Full Name:</b>
  <%= @user.first + " " + @user.last %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @user.phone %>
</p>

<p>
  <b>User Type:</b>
  <%= @user.user_type %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>