config/routes.rb
AssignmentHub::Application.routes.draw do
  resources :universities

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "forgot_password" => "password_resets#new", :as => "forgot_password"
  get "reminder" => "reminders#new", :as => "remind_me"
  get "course_search" => "courses#search", :as => "course_search"
  get "dashboard" => "dashboard#index", :as => "dashboard"

  match 'attachments_for/:assignment_id' => 'Attachments#index'
  match 'assignments/new_for_course/:course_id' => 'Assignments#new'

  root :to => "courses#index", :as => "home"

  resources :teachers

  resources :attachments

  resources :assignments

  resources :courses do
    get :autocomplete_university_name, :on => :collection
  end

  resources :users
  resources :sessions
  resources :password_resets
  resources :reminders
  

end

app/models/teacher.rb
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

class Teacher < ActiveRecord::Base
  has_and_belongs_to_many :courses
  belongs_to :user
  
  validates_presence_of :first, :last
  validates_length_of :first, :last, :maximum => 15, :message => "less than 15 characters please"
  validates_length_of :email, :maximum => 40, :message => "less than 40 characters please"
  validates_length_of :office_hours, :maximum => 50, :message => "less than 50 characters please"
  #validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "Invalid email"
  
  # i wouldn't do that.. what if two users create the same professor record?
  # we need to make the record belong to user
  #validates_uniqueness_of :email
  
  
  
  TITLETYPE = [['Prof.', '4'],
  ['Dr.', '3'],
  ['Mrs.', '2'],
  ['Ms.', '1'],
  ['Mr.', '0']]

  
  has_attached_file :photo, 
                    :default_url => "/assets/NA_:style.jpg", 
                    :styles => {:large => "300x300>", 
                                :small => "150x150>", 
                                :thumb => "57x75#"}
                                                  
  
  
  def self.GetTitleFromValue(value)
    temp = TITLETYPE.select{ |x| x[1] == value.to_s() }.first
    return temp ? temp.first : ''
  end
  
  def self.GetInstructorFullName(instructor)
    return "" if !instructor
      
    title_str = instructor.title ? GetTitleFromValue(instructor.title) + " " : ""
    return title_str + instructor.last + ", " + instructor.first
  end
end

app/controllers/teachers_controller.rb
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

class TeachersController < ApplicationController
  # GET /teachers
  # GET /teachers.json
  def index
    if current_user && User.find(current_user).user_type > 0
      @teachers = Teacher.where(:user_id => User.find(current_user))
    elsif current_user && User.find(current_user).user_type == 0
      @teachers = Teacher.all
    else
      @teachers = nil
      redirect_to sign_up_path and return
    end
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.json
  def new
    @teacher = Teacher.new
    @teacher.user = User.find(current_user)
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(params[:teacher])
    @teacher.user = User.find(current_user)
    
    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render json: @teacher, status: :created, location: @teacher }
      else
        format.html { render action: "new" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.json
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.js   { render :nothing => true }
      format.json { head :no_content }
    end
  end
end

app/helpers/teachers_helper.rb
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

module TeachersHelper
end

app/views/teachers/_form.html.erb
<!--
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-->

<!-- Content -->
<div id="content">
	<%= form_for(@teacher, :html => {:multipart => true}) do |f| %>
	  <% if @teacher.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this user from being saved:</h2>

      
	      <% @teacher.errors.full_messages.each do |msg| %>
			<!-- Message Error -->
			<div class="msg msg-error">
				<p><strong><%= msg %></strong></p>
				<a href="#" class="close">close</a>
			</div>
			<!-- End Message Error -->      
	      <% end %>
      
	    </div>
	  <% end %>

	<!-- Box -->
	<div class="box">
		<!-- Box Head -->
		<div class="box-head">
			<h2>Edit Teacher</h2>
		</div>
		<!-- End Box Head -->
					<!-- Form -->
					<div class="form">
						
						<p>
							<span class="req">(Required)</span>
						  	<%= f.label :title %>
						  	<%= f.select :title, Teacher::TITLETYPE  %>
						</p>
						<p>
						  	<span class="req">(Required, max 15 characters)</span>
						  	<%= f.label "First name" %>
						  	<%= f.text_field :first %>
						</p>
						<p>
						  	<span class="req">(Required, max 15 characters)</span>
						  	<%= f.label "Last name" %>
						  	<%= f.text_field :last %>
						</p>
						<p>
						  	<span class="req">(Required, max 40 characters)</span>
						  	<%= f.label "Email address" %>
						  	<%= f.text_field :email %>
						</p>
						<p>
						  	<%= f.label "Phone number" %>
						  	<%= f.text_field :phone %>
						</p>
						<p>
							<%= f.label "Office Hours" %>
						    <%= f.text_field :office_hours %>
						</p>
						<p>
							<%=f.file_field :photo %>
						</p>
					</div>
					<!-- End Form -->

					<!-- Form Buttons -->
					<div class="buttons">
						<%= link_to 'Back', teachers_path, :class => 'button' %>
						<%= f.submit 'Submit', :class => 'button' %>
					</div>
					<!-- End Form Buttons -->
			</div>
			<!-- End Box -->

			<% end %>

		</div>
		<!-- End Content -->
		

<!-- Sidebar -->
<div id="sidebar">
	
	<!-- Box -->
	<div class="box">
		
		<!-- Box Head -->
		<div class="box-head">
			<h2>Management</h2>
		</div>
		<!-- End Box Head-->
		
		<div class="box-content">
			<%= link_to 'Add New User', new_user_path, :class => 'btn' %>
			<div class="cl">&nbsp;</div>
			
			<p class="select-all"><input type="checkbox" class="checkbox" /><label>select all</label></p>
			<p><a href="#">Delete Selected</a></p>
			
		</div>
	</div>
	<!-- End Box -->
</div>
<!-- End Sidebar -->

app/views/teachers/index.html.erb
<!--
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-->

<!-- Content -->
<div id="content">
	
	<!-- Box -->
	<div class="box">
		<!-- Box Head -->
		<div class="box-head">
			<h2 class="left">Listing Instructors</h2>
			<div class="right">
				
				<label for="search">search instructors</label>
				<input name="search" type="text" class="field small-field" />
				<input type="submit" class="button" value="search" />
			
			</div>
		</div>
		<!-- End Box Head -->	

		<!-- Table -->
		<div class="table">
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<th width="13"><input type="checkbox" class="checkbox" /></th>
				    <th><!--photo--></th>
					<th>Name</th>
				    <th>Email</th>
				    <th>Office hours</th>
				    <th>Phone</th>
				    <% if is_admin %>
						<th>User</th>
					<% end %>
				    <th></th>
				    <th></th>
				  </tr>

				<% @teachers.each do |teacher| %>
				  <tr>
					<td><input type="checkbox" class="checkbox" /></td>
			    	<td><%= image_tag teacher.photo.url(:thumb), :class => "prof_thumb" %></td>
					<td><%= link_to Teacher::GetInstructorFullName(teacher), teacher %></td>
				    <td><%= teacher.email %></td>
				    <td><%= teacher.office_hours %></td>
				    <td><%= teacher.phone %></td>
					<!--will show usernames to which teachers belong to for admin user -->
					<% if is_admin %>
						<td><%= teacher.course.user.name if teacher.course %></td>
					<% end %>
				    <td><%= link_to '', edit_teacher_path(teacher), :class => 'ico edit' %></td>
				    <td><%= link_to '', teacher, confirm: 'Are you sure?', method: :delete, :class => 'delete_from_index ico del', :remote => true %></td>
				  </tr>
				<% end if @teachers %>
			</table>
			
			<% if !@teachers || @teachers.length == 0 %>
				<div class="ac">No Instructors Found... Add one now.</div>
			<% end %>

			<!-- Pagging -->
			<div class="pagging">
				<div class="left">Showing 1-<%= @teachers.length if @teachers %> of <%= @teachers.length if @teachers %></div>
				<div class="right">
					<a href="#">Previous</a>
					<a href="#">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">245</a>
					<span>...</span>
					<a href="#">Next</a>
					<a href="#">View all</a>
				</div>
			</div>
			<!-- End Pagging -->

		</div>
		<!-- Table -->

	</div>
	<!-- End Box -->
	
</div>
<!-- End Content -->

<!-- Sidebar -->
<div id="sidebar">
	
	<!-- Box -->
	<div class="box">
		
		<!-- Box Head -->
		<div class="box-head">
			<h2>Management</h2>
		</div>
		<!-- End Box Head-->
		
		<div class="box-content">
			<%= link_to 'Add New Instructor', new_teacher_path, :class => 'btn' %>
			<div class="cl">&nbsp;</div>
			
			<p class="select-all"><input type="checkbox" class="checkbox" /><label>select all</label></p>
			<p><a href="#">Delete Selected</a></p>
			
		</div>
	</div>
	<!-- End Box -->
</div>
<!-- End Sidebar -->

app/views/teachers/new.html.erb
<!--
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-->

<%= render 'form' %>

app/views/teachers/show.html.erb
<!--
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#TeacherHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-->

<!--
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#TeacherHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-->


<!-- Content -->
<div id="content">
	
	<!-- Box -->
	<div class="box">
		<!-- Box Head -->
		<div class="box-head">
			<h2>Instructor: <%= Teacher::GetInstructorFullName(@teacher) %></h2>
		</div>
		<!-- End Box Head -->
	
	
	<div id="show-page-content" >
			
			<ul class="polaroids">
				<li>
					<a href="#"><%= image_tag @teacher.photo.url(:large) %></a>
				</li>
			</ul>
			<dl class="two-col">
				<li>
					<div>
					  <h3>Name:</h3>
					  <%= Teacher::GetInstructorFullName(@teacher) %>
					</div>

					<div>
					  <h3>Email:</h3>
					  <%= mail_to @teacher.email, @teacher.email %>
					</div>
				</li>
				<li>
					<div>
					  <h3>Office Hours:</h3>
			  		  <%= @teacher.office_hours %>
					</div>

					<div>
					  <h3>Phone</h3>
			  		  <%= @teacher.phone %>
					</div>

				</li>
			</dl>
			<div>
			  <b>Courses:</b><br />
				<dl>
					<% for course in @teacher.courses %>
						<li><%= course.course_number + " - " + course.name %></li>
					<% end %>
				</dl>
			</div>
		</div>
			<!-- Form Buttons -->
			<div class="buttons">
				<%= link_to 'Edit', edit_teacher_path(@teacher), :class => 'button' %>
				<%= link_to 'Back', teachers_path(), :class => 'button' %>
			</div>
			<!-- End Form Buttons -->
	</div>
	<!-- End Box -->

</div>
<!-- End Content -->

<!-- Sidebar -->
<div id="sidebar">
	
	<!-- Box -->
	<div class="box">
		
		<!-- Box Head -->
		<div class="box-head">
			<h2>Management</h2>
		</div>
		<!-- End Box Head-->
		
		<div class="box-content">
			<%= link_to 'Add New Instructor', new_teacher_path, :class => 'btn' %>
			<div class="cl">&nbsp;</div>
			
			
			
		</div>
	</div>
	<!-- End Box -->
</div>
<!-- End Sidebar -->