config/routes.rb
AssignmentHub::Application.routes.draw do
  resources :universities

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "forgot_password" => "password_resets#new", :as => "forgot_password"
  get "reminder" => "reminders#new", :as => "remind_me"
  get "course_search" => "courses#search", :as => "course_search"
  get "dashboard" => "dashboard#index", :as => "dashboard"

  match 'attachments_for/:assignment_id' => 'Attachments#index'
  match 'assignments/new_for_course/:course_id' => 'Assignments#new'

  root :to => "courses#index", :as => "home"

  resources :teachers

  resources :attachments

  resources :assignments

  resources :courses do
    get :autocomplete_university_name, :on => :collection
  end

  resources :users
  resources :sessions
  resources :password_resets
  resources :reminders
  

end

app/controllers/courses_controller.rb
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

class CoursesController < ApplicationController
  
  autocomplete :university, :name, :full => true
  
  # GET /courses
  # GET /courses.json
  def index
    #@courses = Course.all
    
    #this is supposed to show only the courses assigned for the user
    #if false
      if current_user && User.find(current_user).user_type > 0
        @courses = Course.where(:user_id => User.find(current_user))
      elsif current_user && User.find(current_user).user_type == 0
        @courses = Course.all
      else
        @courses = nil
        redirect_to sign_up_path and return
      end
    #end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new
    @course.color = get_random_color
    @last_school_used = last_school_used
    
    #2.times { @course.teachers.build }
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
    @instructors = @course.teachers
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])
    
    # set current user as the creator of the course 
    @course.user = User.find(current_user)
    
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.js
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.js
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.js
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.js
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.js   { render :nothing => true }
      format.json { head :no_content }
    end
  end
  
  def get_random_color
    return "%06x" % (rand * 0xffffff)
  end
  
  def last_school_used
		last_course = Course.where(:user_id => User.find(current_user)).find(:first, :order => "updated_at DESC", :limit => 1)
		if last_course
			last_school_used = last_course.school
    end
  end
  
  # GET /courses/1
  # GET /courses/1.json
  def search(search)
    #@courses = Course.where(:published => true).find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    courses_tbl = Course.arel_table
    @courses = Course.where(:published => true)
    
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @course }
    end
  end
  
end

app/helpers/courses_helper.rb
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

module CoursesHelper
end

app/views/courses/_form.html.erb
<!--
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-->

<%= stylesheet_link_tag "colorpicker", :media => "all" %>
<%= javascript_include_tag "colorpicker" %>
<%= javascript_include_tag "colorpicker-setup" %>

<!-- Content -->
<div id="content">
	<%= form_for(@course, :remote => true, :builder => ApplicationHelper::ColorPickerFormBuilder) do |f| %>
	  <% if @course.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      
	      <% @course.errors.full_messages.each do |msg| %>
			<!-- Message Error -->
			<div class="msg msg-error">
				<p><strong><%= msg %></strong></p>
				<a href="#" class="close">close</a>
			</div>
			<!-- End Message Error -->      
	      <% end %>
      
	    </div>
	  <% end %>

	<!-- Box -->
	<div class="box">
		<!-- Box Head -->
		<div class="box-head">
			<h2>Edit Course</h2>
		</div>
		<!-- End Box Head -->
			
			<div id="ajax-response" class="hidden">
			</div>
		
			<!-- Form -->
			<div class="form">
			  <p>
				<%= f.label :color %>
				<%= f.hidden_field :color %>
				<div id="customWidget">
					<div id="colorSelector"><div style="background-color: <%= @course.color ? '#' + @course.color : '#0066ff'%>"></div></div>
	                <div id="colorpickerHolder">
	                </div>
				</div>
			  </p>
			  <p>
				<span class="req">(Required, max 100 symbols)</span>
				<%= f.label :name %>
			    <%= f.text_field :name %>
			  </p>
			  <p>
				<span class="req">(Required, max 10 symbols)</span>
			    <%= f.label :course_number %>
			    <%= f.text_field :course_number %>
			  </p>
			  <p>
			    <%= f.label :section %>
			    <%= f.text_field :section %>
			  </p>
			  <p>
			    <%= f.label :school %>
			    <%= f.autocomplete_field :school, autocomplete_university_name_courses_path %>
			  </p>
			  <p>
				<%= f.label :teachers, "Instructors:" %>
				<%= f.fields_for :teachers do |ff| %>
				    <%= render 'teacher_fields', :f => ff %>
				<% end %>
				<p><%= link_to_add_fields "Add Instructor", f, :teachers %></p>
			  </p>
			  <p>
			    <%= f.label :published, "Publish?" %>
				<%= f.check_box :published %>
			  </p>
			  

			 <p id="code" class="hidden">
			    <%= f.label :code, "Publishing Code" %>
			    <%= f.text_field :code %>
			  </p>
			</div>
			<!-- End Form -->
		
			<!-- Form Buttons -->
			<div class="buttons">
				<%= link_to 'Back', courses_path, :class => 'button' %>
				<%= f.submit 'Submit', :class => 'button' %>
			</div>
			<!-- End Form Buttons -->
	</div>
	<!-- End Box -->
		
		<script language="javascript">
			//initial setup (hide code if not published)
		  	if (<%=@course.published%>)
				$("#code").toggle();

			//script to toggle the course textbox when the published checkmark is clicked	
			$("#course_published").click(function(){
				$("#code").toggle("slow");
			});

			// script to automatically fill in last university used in the system for new course entries
			if (<%=!@course.id%>)
				$("#course_school").val("<%=@last_school_used%>");
			
		 </script>

	<% end %>

</div>
<!-- End Content -->

<!-- Sidebar -->
<div id="sidebar">
	
	<!-- Box -->
	<div class="box">
		
		<!-- Box Head -->
		<div class="box-head">
			<h2>Management</h2>
		</div>
		<!-- End Box Head-->
		
		<div class="box-content">
			<%= link_to 'Add New Course', new_course_path, :class => 'btn' %>
			<div class="cl">&nbsp;</div>
			
			<p class="select-all"><input type="checkbox" class="checkbox" /><label>select all</label></p>
			<p><a href="#">Delete Selected</a></p>
			
		</div>
	</div>
	<!-- End Box -->
</div>
<!-- End Sidebar -->

app/views/courses/_teacher_fields.html.erb
<!--
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-->

<p class="fields">
	<!-- insecure - find a way to intercept this call and set user id on server side -->
	<%= f.hidden_field :user_id, :value => User.find(current_user).id.to_s %>
	<%= f.label :first, :class => 'subform_label' %>
 	<%= f.text_field :first, :class => 'subform_textfield' %>
    <%= f.label :last, :class => 'subform_label' %>
    <%= f.text_field :last, :class => 'subform_textfield' %>
	<%= f.label :instructor_type, "Role", :class => 'subform_label' %>
	<%= select_tag(:instructor_type, 
		options_for_select([['Professor', 'PR'],['Teaching Assistant', 'TA'],['Adjunct Professor', 'AD']]),
		:class => 'subform_combo')  %>
 	<%= link_to_remove_fields "remove", f %>
</p>

app/views/courses/index.html.erb
<!--
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-->

<!-- Content -->
<div id="content">
	
	<!-- Box -->
	<div class="box">
		<!-- Box Head -->
		<div class="box-head">
			<h2 class="left">Listing Courses</h2>
			<div class="right">
				
				<label for="search">search courses</label>
				<input name="search" type="text" class="field small-field" />
				<input type="submit" class="button" value="search" />
				
				<% form_tag course_search_path, :method => 'get' do %>
				    <%= text_field_tag :search, params[:search] %>
				    <%= submit_tag "Search", :name => nil %>
				<% end %>
			</div>
		</div>
		<!-- End Box Head -->	

		<!-- Table -->
		<div class="table">
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<th width="13"><input type="checkbox" class="checkbox" /></th>
				    <th></th>
					<th>Name</th>
				    <th>Course number</th>
				    <th>School</th>
				    <th>Section</th>
				    <th>Code</th>
				    <% if is_admin %>
						<th>User</th>
					<% end %>
				    <th></th>
				    <th></th>
				  </tr>

				<% @courses.each do |course| %>
				  <tr>
					<td><input type="checkbox" class="checkbox" /></td>
					<td><div class="course-color-index" style="background:#<%= course.color %>;" /></td>
				    <td><%=link_to course.name, course %></td>
				    <td><%= course.course_number %></td>
				    <td><%= course.school %></td>
				    <td><%= course.section %></td>
					<!--will show [N/A] for unpublished courses-->
				    <td><%= course.published ? course.code : "[N/A]" %></td>
					<!--will show usernames to which courses belong to for admin user -->
					<% if current_user && User.find(current_user).user_type == 0 %>
						<td><%= course.user.name if course.user %></td>
					<% end %>
				    <td><%= link_to '', edit_course_path(course), :class => 'ico edit' %></td>
				    <td><%= link_to '', course, confirm: 'Are you sure?', method: :delete, :class => 'delete_from_index ico del', :remote => true %></td>
				  </tr>
				<% end if @courses %>
			</table>
			
			<% if !@courses || @courses.length == 0 %>
				<div class="ac">No Courses Found... Add one now.</div>
			<% end %>

			<!-- Pagging -->
			<div class="pagging">
				<div class="left">Showing 1-<%= @courses.length if @courses %> of <%= @courses.length if @courses %></div>
				<div class="right">
					<a href="#">Previous</a>
					<a href="#">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">245</a>
					<span>...</span>
					<a href="#">Next</a>
					<a href="#">View all</a>
				</div>
			</div>
			<!-- End Pagging -->

		</div>
		<!-- Table -->

	</div>
	<!-- End Box -->
	
</div>
<!-- End Content -->

<!-- Sidebar -->
<div id="sidebar">
	
	<!-- Box -->
	<div class="box">
		
		<!-- Box Head -->
		<div class="box-head">
			<h2>Management</h2>
		</div>
		<!-- End Box Head-->
		
		<div class="box-content">
			<%= link_to 'Add New Course', new_course_path, :class => 'btn' %>
			<div class="cl">&nbsp;</div>
			
			<p class="select-all"><input type="checkbox" class="checkbox" /><label>select all</label></p>
			<p><a href="#">Delete Selected</a></p>
			
		</div>
	</div>
	<!-- End Box -->
</div>
<!-- End Sidebar -->

app/views/courses/search.html.erb
<!--
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#AssignmentHub - My School Organizer on the Cloud
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Copyright (C) 2012 Dorian Karter, Joseph Low, Amar Rana
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#documentation files (the "Software"), to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
#to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions
#of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
#TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#DEALINGS IN THE SOFTWARE.
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
-->

<!-- Content -->
<div id="content">
	
	<!-- Box -->
	<div class="box">
		<!-- Box Head -->
		<div class="box-head">
			<h2 class="left">Listing Courses</h2>
			<div class="right">
				
				<label>search courses</label>
				<!--input type="text" class="field small-field" /-->
				<!--input type="submit" class="button" value="search" /-->
				<% form_tag course_search_path, :method => 'get' do %>
				  
				    <%= text_field_tag :search, params[:search] %>
				    <%= submit_tag "Search", :name => nil %>
				<% end %>
			</div>
		</div>
		<!-- End Box Head -->	

		<!-- Table -->
		<div class="table">
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<th width="13"><input type="checkbox" class="checkbox" /></th>
				    <th></th>
					<th>Name</th>
				    <th>Course number</th>
				    <th>School</th>
				    <th>Section</th>
				    <th>Code</th>
				    <% if is_admin %>
						<th>User</th>
					<% end %>
				    <th></th>
				    <th></th>
				    <th></th>
				  </tr>

				<% @courses.each do |course| %>
				  <tr>
					<td><input type="checkbox" class="checkbox" /></td>
					<td><div style="display: block; background:#<%= course.color%>; width:20px; height:20px;" /></td>
				    <td><%= course.name %></td>
				    <td><%= course.course_number %></td>
				    <td><%= course.school %></td>
				    <td><%= course.section %></td>
					<!--will show [N/A] for unpublished courses-->
				    <td><%= course.published ? course.code : "[N/A]" %></td>
					<!--will show usernames to which courses belong to for admin user -->
					<% if is_admin %>
						<td><%= course.user.name if course.user %></td>
					<% end %>
				    <td><%= link_to 'Show', course %></td>
				    <td><%= link_to 'Edit', edit_course_path(course), :class => 'ico edit' %></td>
				    <td><%= link_to 'Destroy', course, confirm: 'Are you sure?', method: :delete, :class => 'delete_course ico del', :remote => true %></td>
				  </tr>
				<% end if @courses %>
			</table>
			
			<% if !@courses || @courses.length == 0 %>
				<div class="ac">No Courses Found... Add one now.</div>
			<% end %>

			<!-- Pagging -->
			<div class="pagging">
				<div class="left">Showing 1-<%= @courses.length if @courses %> of <%= @courses.length if @courses %></div>
				<div class="right">
					<a href="#">Previous</a>
					<a href="#">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">245</a>
					<span>...</span>
					<a href="#">Next</a>
					<a href="#">View all</a>
				</div>
			</div>
			<!-- End Pagging -->

		</div>
		<!-- Table -->

	</div>
	<!-- End Box -->
	
</div>
<!-- End Content -->

<!-- Sidebar -->
<div id="sidebar">
	
	<!-- Box -->
	<div class="box">
		
		<!-- Box Head -->
		<div class="box-head">
			<h2>Management</h2>
		</div>
		<!-- End Box Head-->
		
		<div class="box-content">
			<%= link_to 'Add New Course', new_course_path, :class => 'btn' %>
			<div class="cl">&nbsp;</div>
			
			<p class="select-all"><input type="checkbox" class="checkbox" /><label>select all</label></p>
			<p><a href="#">Delete Selected</a></p>
			
		</div>
	</div>
	<!-- End Box -->
</div>
<!-- End Sidebar -->